# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Define the prompt format
format = """
[](user_os_bg)\
$os\
$username\
[](bg:path_bg fg:user_os_bg)\
$directory\
[](fg:path_bg bg:git_bg)\
$git_branch\
$git_status\
[](fg:git_bg bg:tooling_bg)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:tooling_bg bg:endcap_bg)\
$docker_context\
[](fg:endcap_bg bg:time_bg)\
$time\
[ ](fg:time_bg)\
"""

# Set the palette
palette = 'pastel'

# Define palette's
[palettes.pastel]
user_os_bg = '#9A348E'
user_os_fg = '#ebc5e7'
tooling_bg = '#86BBD8'
tooling_fg = '#263841'
path_bg = '#DA627D'
path_fg = '#ecd5c7'
git_bg = '#FCA17D'
git_fg = '#442b22'
time_bg = '#33658A'
time_fg = '#c3d6e5'
endcap_bg = '#06969A'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:user_os_fg bg:user_os_bg"
style_root = "fg:user_os_fg bg:user_os_bg"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:user_os_bg"
disabled = true # Disabled by default

[directory]
style = "fg:path_fg bg:path_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:endcap_bg"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:git_fg bg:git_bg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:git_fg bg:git_bg"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:tooling_fg bg:tooling_bg"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%-l:%M %p"
style = "fg:time_fg bg:time_bg"
format = '[  $time ]($style)'
